name: Build HTML from Notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nbconvert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert jupyter

      - name: Convert notebook to HTML (docs/index.html)
        run: |
          mkdir -p docs
          jupyter nbconvert --to html "Proyecto9_Megaline.ipynb" --output "index.html" --output-dir docs

      - name: Commit generated HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "chore: auto-build HTML for GitHub Pages" || echo "No changes to commit"
          git push
